### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Xapuu** [SoftUni/Programming-Basics-Book-JS-BG#36]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-JS-BG/blob/master/chapter-11-tricks-and-hacks.md

## Описание

Правописна грешка виж : [Дефиниция на БАН](http://ibl.bas.bg/rbe/lang/bg/браузър/)

## Текущ текст

... ето на един от първите ```браузери``` Netscape ...

## Текст след поправката
... ето на един от първите ```браузъри``` Netscape ...

**Comment by nakov** [comment]
fixed
