### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Xapuu** [SoftUni/Programming-Basics-Book-JS-BG#37]
## Линк към файла

https://github.com/SoftUni/Programming-Basics-Book-JS-BG/blob/master/chapter-11-tricks-and-hacks.md

## Описание

Правописна грешка

## Текущ текст

"...отворете Visual Studio Code ```натисните``` [CTRL + K + S] ..." 

## Текст след поправката

"...отворете Visual Studio Code ```натиснете``` [CTRL + K + S] ..."

**Comment by nakov** [comment]
fixed, thanks
