### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Xapuu** [SoftUni/Programming-Basics-Book-JS-BG#38]
## Линк към файла

https://github.com/SoftUni/Programming-Basics-Book-JS-BG/blob/master/chapter-11-tricks-and-hacks.md

## Описание

typo

## Текущ текст

"// Това e ```применлива``` от тип масив"

## Текст след поправката

"// Това e ```променлива``` от тип масив"

**Comment by nakov** [comment]
Thanks, fixed.
