### ISSUE TITLE
Ударения

### ISSUE THREAD

**Issue by dabidesh** [SoftUni/Programming-Basics-Book-JS-BG#43]
## Линк към файла
https://js-book.softuni.bg/chapter-02-simple-calculations-exam-problems.html#%D0%B8%D0%B7%D0%B2%D0%B5%D0%B6%D0%B4%D0%B0%D0%BD%D0%B5-%D0%BD%D0%B0-%D1%82%D0%B5%D0%BA%D1%81%D1%82-%D0%BF%D0%BE-%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD-placeholder
## Описание
Ударения, а не наклонени кавички (апострофи)
## Текущ текст
наклонени кавички (апострофи) `…` 
## Текст след поправката
ударения (grave accent)  `…`

**Comment by nakov** [comment]
Попавено:
  - https://github.com/SoftUni/Programming-Basics-Book-JS-BG/blob/master/chapter-02-simple-calculations.md
  - https://github.com/SoftUni/Programming-Basics-Book-JS-BG/blob/master/chapter-02-simple-calculations-exam-problems.md
  
Решихме да ползваме термина **"наклонен апостроф" (backtick)**.
