### ISSUE TITLE
Цикъл

### ISSUE THREAD

**Issue by dabidesh** [SoftUni/Programming-Basics-Book-JS-BG#44]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-JS-BG/blob/master/chapter-06-nested-loops.md
## Описание
Цикълът ще се изпълни 11 пъти
## Текущ текст
i<=10
## Текст след поправката
i<10

**Comment by dabidesh** [comment]
Някъде бях чел, че подобни цикли е добре да започват от 0 за да не стават обърквания.
Иначе може да се оправи и с „i=1“.

**Comment by nakov** [comment]
Да, имаше бъг. Поправих го. Благодаря!
