### ISSUE TITLE
Примерен изход

### ISSUE THREAD

**Issue by dabidesh** [SoftUni/Programming-Basics-Book-JS-BG#45]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-JS-BG/blob/master/chapter-08-exam-preparation.md#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D0%B5%D0%BD-%D0%B2%D1%85%D0%BE%D0%B4-%D0%B8-%D0%B8%D0%B7%D1%85%D0%BE%D0%B4-7
## Описание
Последният примерен изход е грешен!
## Текущ текст
4
## Текст след поправката
5

**Comment by dabidesh** [comment]
Според мен програмата е правилна, но дава резултат 58/100!

**Comment by Xapuu** [comment]
@dabidesh  Предполжената поправка може и да не е коректна, понеже задачата може да се реши със 100/100 в judge със следното решение

```javascript
function test(input){
 let countCurrentLongest = 0;
 let countLongest = 0;
 let numPrev = -Infinity;
 let num = 0;

 for (let i = 1; i < input.length; i++){
     num = +input[i];
   
     if(num > numPrev){
       countCurrentLongest+=1;
     } else {
	   countCurrentLongest = 1;
     }

     if (countCurrentLongest > countLongest) {
		countLongest = countCurrentLongest;
     }

	numPrev = num;
 }

  return countLongest;
}
```

Относно коректността на решението на задачата, има два проблема.

1. Входните данни идват като масив от стрингове, така че всяко число трябва да бъде конвертирано към `Number` преди да бъдат направени съответните сравнения.

2. Възможно е условието което е предоставено в кингата да не е пълно
```
Дадена е редица от n числа: a1, a2, …, an. Да се пресметне дължината на най-дългата нарастваща поредица от последователни елементи в редицата от числа.
```
или тестовете които са здадени в judge да са коректни, за съжаление обаче, няма как да проверя това. 

Ако е възможно @nakov да бъде тагнат някой, който може да потвърди дали условето е пълно или тестовете в judge са грешни, ще е супер.

**Comment by nakov** [comment]
Става дума за тази задача, нали?

[Задача: поредица от нарастващи елементи](https://github.com/SoftUni/Programming-Basics-Book-JS-BG/blob/master/chapter-08-exam-preparation.md#%D0%B7%D0%B0%D0%B4%D0%B0%D1%87%D0%B0-%D0%BF%D0%BE%D1%80%D0%B5%D0%B4%D0%B8%D1%86%D0%B0-%D0%BE%D1%82-%D0%BD%D0%B0%D1%80%D0%B0%D1%81%D1%82%D0%B2%D0%B0%D1%89%D0%B8-%D0%B5%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%B8)

Решението на Хари е коректно и работи правилно.

Объркването вероятно идва от факта, че входният масив съдържа в началото си броя елементи (числото **n**) и след него същинските **n** елемента, сред които се търси поредицата нарастващи елементи.
