### ISSUE TITLE
Specify font size

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-JS-BG#6]
Моля да се измери и зададе какъв **размер шрифт** ще се ползва за **code screenshots**.

Да се уточни това в [записките](https://github.com/SoftUni/Programming-Basics-Book-JS-BG/wiki/%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D0%BA%D0%B8-%D0%BE%D1%82-%D1%83%D1%87%D1%80%D0%B5%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D0%BD%D0%B0%D1%82%D0%B0-%D1%81%D1%80%D0%B5%D1%89%D0%B0-%D0%BD%D0%B0-%D0%B5%D0%BA%D0%B8%D0%BF%D0%B0) и [ръководството на авторите](https://github.com/SoftUni/Programming-Basics-Book-JS-BG/wiki/%D0%9D%D0%B0%D1%81%D0%BE%D0%BA%D0%B8-%D0%BA%D1%8A%D0%BC-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D1%82%D0%B5).

**Comment by Stilyan-Kangalov** [comment]
Измерено и добавено на двете страници.
